// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Xamarin.Crash
{
	public partial class CrashButton : UIButton
	{
		public CrashButton (IntPtr handle) : base (handle)
		{
		}
	}
}
